### ISSUE TITLE
Support multiple sites for DOC collection

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/sitewide-search-app#167]
### Issue description
*Description of the issue.*
*NOTE: Determine if this change will impact existing piece(s) of documentation (e.g., comps, instruction files, etc.). If so, create a new ticket for the associated updates to be completed after Drupal development (or final stage) is completed.*

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by blairlearn** [comment]
In order to preserve existing site configurations which only need a single site filter value, the `searchSiteFilter` configuration value is modified to be either a single string (e.g. `"searchSiteFilter": "www.cancer.gov\/nano"`) or an array (e.g. `"searchSiteFilter": ["dceg.cancer.gov","www.cancer.gov\/connect-prevention-study"]`)

In the application's `initialize` method, `searchSiteFilter` is converted to an array of strings if it isn't one already and that array is passed to the API as a list of query string parameters (e.g. `site=dceg.cancer.gov&site=www.cancer.gov/connect-prevention-study`)

**Comment by santwuma** [comment]
Closed by #171
